#include <project.h>

/* There are 16 input channels */
#define NUMCHAN (16u)

/* DMA configuration constants for DMA_1 */
#define DMA_1_BYTES_PER_BURST (2u)
#define DMA_1_REQUEST_PER_BURST (1u)
#define DMA_1_SRC_BASE (CYDEV_PERIPH_BASE)
#define DMA_1_DST_BASE (CYDEV_SRAM_BASE)

/* 16-bit wide SRAM buffer with 16 locations into which DMA writes ADC readings */
uint16 result[NUMCHAN];

void DMA_Config(void);


/*******************************************************************************
* Function Name: main
********************************************************************************
*
* Summary:
*  main() performs following functions:
*  1: Starts the components
*  2: Calls function DMA_Config to setup the DMA.
*  3: Starts ADC continuous conversion.
*  4: Gets the converted result and displays it in LCD. Also displays VDAC data
*     register value on LCD.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
int main()
{
    /* Initialize variable that indicates which mux channel is displayed on LCD */
    uint8 curChan = 0u;

    LCD_Start();
    ADC_Start();
    Delay_PWM_Start();

    DMA_Config();

    /* Enable ADC SOC to be triggered by PWM output */
    Start_Reg_Write(1u);

    for(;;)
    {
        /*LCD_ClearDisplay();
        LCD_PrintString("Channel: ");
        LCD_PrintNumber(curChan);

        LCD_Position(1u, 0u);
        LCD_PrintNumber(result[curChan]);
*/
        /* For ease of reading LCD */
  //      CyDelay(100u/*ms*/);

        /* If SW2 is pressed */
       // if(!ChannelSelect_Read())
      //  {
            /* Wait until button is released */
    /*        while(!ChannelSelect_Read())
            {
            }
*/
            /* Increment to next channel for display */
            curChan++;

            /* If we are at channel 16, reset to channel 0 */
            if(curChan == NUMCHAN)
            {
                curChan = 0u;
            }
       }
    //}
}


/*******************************************************************************
* Function Name:  DMA_Config
********************************************************************************
*
* Summary:
*    Code generated by the DMA Wizard.
*
*    DMA_Config() performs following functions:
*  1: Initializes the DMA channel
*  2: Allocates Transfer Descriptors
*  3: Configures the TD.
*  4: Sets source and destination address for this TD.
*  5: Initializes the TD.
*  6: Enables the DMA channel.
*
* Parameters:
*  None.
*
* Return:
*  None.
*
*******************************************************************************/
void DMA_Config()
{
    /* Variable declarations for DMA_1 */
    uint8 DMA_1_Chan;
    uint8 DMA_1_TD[1];

    /* Iniitialize DMA channel */
    DMA_1_Chan = DMA_1_DmaInitialize(DMA_1_BYTES_PER_BURST, DMA_1_REQUEST_PER_BURST,
        HI16(DMA_1_SRC_BASE), HI16(DMA_1_DST_BASE));

    /* Allocate TD */
    DMA_1_TD[0] = CyDmaTdAllocate();

    /* TD configuration setting */
    #if (CY_PSOC3)
        CyDmaTdSetConfiguration(DMA_1_TD[0], 2u * NUMCHAN, DMA_1_TD[0], TD_SWAP_EN | TD_INC_DST_ADR);
    #else
        CyDmaTdSetConfiguration(DMA_1_TD[0], 2u * NUMCHAN, DMA_1_TD[0], TD_INC_DST_ADR);
    #endif

    /* Set Source and Destination address */
    CyDmaTdSetAddress(DMA_1_TD[0], LO16((uint32)ADC_DEC_SAMP_PTR), LO16((uint32)result));

    /* TD initialization */
    CyDmaChSetInitialTd(DMA_1_Chan, DMA_1_TD[0]);

    /* Enable the DMA channel */
    CyDmaChEnable(DMA_1_Chan, 1u);

}


/* [] END OF FILE */
