/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "A0_aliases.h"
#include "A0.h"
#include "isr_glitch.h"
#include "Clock_1.h"
#include "isrEnvio.h"
#include "UART.h"
#include "isrRX.h"
#include "Boton_aliases.h"
#include "Boton.h"
#include "LED_aliases.h"
#include "LED.h"
#include "WaveDAC8_1.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "s0_aliases.h"
#include "s0.h"
#include "s1_aliases.h"
#include "s1.h"
#include "s2_aliases.h"
#include "s2.h"
#include "s3_aliases.h"
#include "s3.h"
#include "ADC_AMux.h"
#include "ADC_Ext_CP_Clk.h"
#include "ADC_IRQ.h"
#include "ADC_theACLK.h"
#include "UART_IntClock.h"
#include "WaveDAC8_1_DacClk.h"
#include "WaveDAC8_1_Wave1_DMA_dma.h"
#include "WaveDAC8_1_Wave2_DMA_dma.h"
#include "WaveDAC8_1_VDAC8.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

